# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Security\AuthenticationSuccessHandler:
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
        tags:
            - { name: monolog.logger, channel: security }

    App\Service\SandboxConnectionFactory:
        public: true

    App\Service\SandboxQueryExecutor:
        arguments:
            $connectionFactory: '@App\Service\SandboxConnectionFactory'

    App\Service\SandboxManager:
        arguments:
            $params: '@parameter_bag'
            $queryExecutor: '@App\Service\SandboxQueryExecutor'

    App\Service\SandboxLogService:
        arguments:
            $sandboxLogRepository: '@App\Repository\SandboxLogRepository'
            $entityManager: '@doctrine.orm.entity_manager'

    App\Service\ExerciseService:
        arguments:
            $exerciseRepository: '@App\Repository\ExerciseRepository'
            $progressRepository: '@App\Repository\UserExerciseProgressRepository'
            $entityManager: '@doctrine.orm.entity_manager'
            $sandboxManager: '@App\Service\SandboxManager'

    App\Service\AiAssistantService:
        arguments:
            $aiConversationRepository: '@App\Repository\AiConversationRepository'
            $entityManager: '@doctrine.orm.entity_manager'
            $httpClient: '@http_client'
            $aiEnabled: '%env(AI_ENABLED)%'
            $aiProvider: '%env(AI_PROVIDER)%'
            $aiApiKey: '%env(AI_API_KEY)%'
            $aiBaseUrl: '%env(AI_BASE_URL)%'
            $aiModel: '%env(AI_MODEL)%'
            $aiMaxTokens: '%env(int:AI_MAX_TOKENS)%'
            $aiTemperature: '%env(float:AI_TEMPERATURE)%'

    Symfony\Contracts\HttpClient\HttpClientInterface:
        class: Symfony\Component\HttpClient\HttpClient
        factory: ['Symfony\Component\HttpClient\HttpClient', 'create']
